version: '3'

services:
#  redis:
#    image: redis:alpine
#    ports:
#      - 6379:6379
#    networks:
#      - backend
  
  postgres:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cartola
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
  
#  cartola-coltec-service:
#    build:
#      context: ./src/services/cartola-service
#      dockerfile: Dockerfile
#    volumes:
#      - ./:/go/src/github.com/gegen07/cartola-university
#    ports:
#      - "8080"
#    depends_on:
#      - redis
#      - postgres
#    networks:
#      - backend
#      - frontend
    
  # cartola-coltec-query
  # elasticseacrh
  # logstash

#  nginx:
#    build:
#      context: ./dockerfiles/nginx
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8000
#    depends_on:
#      - cartola-coltec-service
#    networks:
#      - frontend
  
volumes:
  pgdata:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge