version: '3'

services:
  redis: 
    image: redis:alpine
    ports: 
      - 6379:6379
    networks:
      - backend
  
  postgres:
    image: postgres:11
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cartola
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
  
  cartola-coltec-service:
    build:
      context: ./dockerfiles/go-service
      dockerfile: Dockerfile
    volumes:
      - ./app/cartola-coltec-service:/go/src/github.com/gegen07/cartola-coltec/app/cartola-coltec-service
    depends_on:
      - redis
      - postgres
    networks:
      - backend
      - frontend
    
  # cartola-coltec-query
  # elasticseacrh
  # logstash

  nginx:
    build:
      context: ./dockerfiles/nginx
      dockerfile: Dockerfile
    volumes_from:
      - cartola-coltec-service
    ports:
      - 8080:8000
    networks:
      - frontend
  
volumes:
  pgdata:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge